### PR TITLE
feat: useIsMobileHook

### PR DESCRIPTION
**Pull request by awilderink**

### CODE REVIEW

**Comment by leeuwis** [comment]
@awilderink I think it would be nice if it's more dynamic, so not only for checking if it's mobile (name also isn't totally correct since it's actually just screen width check). So that you can check if the width is below/above a certain size, or between two sizes.

Proposed syntax:
`useHasScreenWidth(min: number, max?: number)`

In the project it could be used as:
`const isMobile = !useHasScreenWidth(theme.breakpoints.mobile)`

OT: Other feature that could be handy `useIsTouchScreen()`

**Comment by MrBamBam** [comment]
I think Doeke has a valid point in this hook being more than just isMobile.

I also believe we should not include theme-ui in the deps for a re-usable hook like this.

So probably the best way to go about this is to refactor it what Doeke suggested and accept a screenWidth (number).

**Comment by awilderink** [comment]
I thought the same while creating the hook, I saw some examples on the web like this one: 

```typescript
// Hook
const useMedia = <T>(queries: string[], values: T[], defaultValue: T) => {
  // Array containing a media query list for each query
  const mediaQueryLists = queries.map(q => window.matchMedia(q));

  // Function that gets value based on matching media query
  const getValue = () => {
    // Get index of first media query that matches
    const index = mediaQueryLists.findIndex(mql => mql.matches);
    // Return related value or defaultValue if none
    return values?.[index] || defaultValue;
  };

  // State and setter for matched value
  const [value, setValue] = useState<T>(getValue);

  useEffect(
    () => {
      // Event listener callback
      // Note: By defining getValue outside of useEffect we ensure that it has ...
      // ... current values of hook args (as this hook callback is created once on mount).
      const handler = () => setValue(getValue);
      // Set a listener for each media query with above handler as callback.
      mediaQueryLists.forEach(mql => mql.addListener(handler));
      // Remove listeners on cleanup
      return () => mediaQueryLists.forEach(mql => mql.removeListener(handler));
    },
    [] // Empty array ensures effect is only run on mount and unmount
  );

  return value;
}
```

How about that?

**Comment by leeuwis** [comment]
Can be nice but also seems a lot harder to use, there are not that many media query types and it would probably be a lot easier to use if we offer something like: `useHasScreenWidth`, `useHasScreenHeight` & `useIsLandscape`

If you combine them you probably cover at least 99% of the use cases. Most of the time you probably don't even have to combine them.

**Comment by leeuwis** [comment]
@awilderink I think we should include the min and max in the check, resulting in:

```
return min <= screenWidth && (max === undefined || screenWidth <= max);
```

Best to also add tests for equality to prevent confusion.

**Comment by awilderink** [comment]
But it is already doing that?

**Pull request merged**
